import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

import Link from "next/link";

import MatrixScrollbar from "@/components/custom_ui/matrix-scrollbar";
import Navbar from "@/components/custom_ui/navbar";
import { ThemeProvider } from "@/components/custom_ui/theme-provider";
import ThemeToggle from "@/components/custom_ui/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col pr-5">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TooltipProvider>
            <MatrixScrollbar />
            <header className="flex items-center justify-between p-2 border-b fixed w-full bg-background z-30">
              <Link href="/">
                <h1 className="font-mono">./Samuel</h1>
              </Link>

              <Navbar />

              <div>
                <ThemeToggle />
              </div>
            </header>
            {children}
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
